[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.8"
aiohttp = "^3.9.5"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
