cargo:
- changed-files:
  - any-glob-to-any-file: cargo/**

cpan:
- changed-files:
  - any-glob-to-any-file: cpan/**

dotnet:
- changed-files:
  - any-glob-to-any-file: dotnet/**

dub:
- changed-files:
  - any-glob-to-any-file: dub/**

go:
- changed-files:
  - any-glob-to-any-file:
    - go-get/**
    - go-modules/**

gradle:
- changed-files:
  - any-glob-to-any-file: gradle/**

node:
- changed-files:
  - any-glob-to-any-file: node/**

npm:
- changed-files:
  - any-glob-to-any-file: npm/**

opam:
- changed-files:
  - any-glob-to-any-file: opam/**

pip:
- changed-files:
  - any-glob-to-any-file: pip/**

poetry:
- changed-files:
  - any-glob-to-any-file: poetry/**

ruby:
- changed-files:
  - any-glob-to-any-file: ruby/**

swift:
- changed-files:
  - any-glob-to-any-file: spm/**

yarn:
- changed-files:
  - any-glob-to-any-file: yarn/**

CI:
- changed-files:
  - any-glob-to-any-file: .github/**
