name: Bug Report
description: Report a bug in some of the flatpak-builder tools
labels:
  - "bug"
body:
  - id: flatpak-builder-version
    type: input
    attributes:
      label: flatpak-builder version
      description: >-
        What version of flatpak-builder are you using?
        If unsure, run `flatpak-builder --version` in the terminal.
      placeholder: 1.2.0
    validations:
      required: true

  - id: os-info
    type: input
    attributes:
      label: Linux distribution and version
      description: >-
        What Linux distribution are you using? If unsure, run `uname -a` in the terminal.
      placeholder: "Ubuntu 20.04"
    validations:
      required: true

  - id: tool-name
    type: dropdown
    attributes:
      label: Affected flatpak-builder tool
      description: >-
        What tool are you experiencing problem with?
        Please specify the script file name in this repository.
      options:
        - cargo/flatpak-cargo-generator.py
        - cpan/flatpak-cpan-generator.pl
        - dotnet/flatpak-dotnet-generator.py
        - dub/flatpak-dub-generator.py
        - go-get/flatpak-go-get-generator.py
        - go-get/flatpak-go-vendor-generator.py
        - node/flatpak-node-generator.py
        - npm/flatpak-npm-generator.py
        - pip/flatpak-pip-generator
        - poetry/flatpak-poetry-generator.py
        - rubygems/flatpak_rubygems_generator.rb
        - yarn/flatpak-yarn-generator.py
    validations:
      required: true

  - id: tool-args
    type: input
    attributes:
      label: flatpak-builder tool cli args
      description: >-
        If you're passing additional command-line options to the tool, specify them here.
      placeholder: --xdg-layout --electron-ffmpeg=archive
    validations:
      required: false

  - id: source-url
    type: input
    attributes:
      label: Source repository URL
      description: >-
        Source URL for the project you're running the tool against.
        If the tool is taking a lockfile as input (e.g. node or cargo generators),
        please link the repository containing the lockfile.
      placeholder: https://github.com/microsoft/vscode.git
    validations:
      required: false

  - id: manifest-url
    type: input
    attributes:
      label: Flatpak-builder manifest URL
      description: >-
        URL for the flatpak-builder manifest you're building.
        Please link the app manifest which references generated-sources produced by the tool,
        not the generated-sources manifest itself.
      placeholder: https://github.com/flathub/com.visualstudio.code-oss.git
    validations:
      required: false

  - id: description
    type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem.
      placeholder: |
        When trying to build the manifest generated by TOOL from LOCKFILE, it gives this error: ...
    validations:
      required: true
