[tool.poetry]
name = "flatpak_node_generator"
version = "0.1.0"
description = ""
authors = ["Ryan Gonzalez <ryan.gonzalez@collabora.com>", "Filippe LeMarchand <gasinvein@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "^3.9.0"

[tool.poetry.dev-dependencies]
blue = {git = "https://github.com/grantjenks/blue"}
isort = "^5.10.1"
mypy = "^0.950"
poethepoet = "^0.13.1"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
pytest-datadir = "^1.3.1"
pytest-httpserver = "^1.0.4"
pytest-xdist = "^2.5.0"

[tool.poetry.scripts]
flatpak-node-generator = "flatpak_node_generator.main:main"

[tool.blue]
line-length = 88
target-version = ["py38"]

[tool.isort]
from_first = true
lines_between_types = 1
profile = "black"
src_paths = ["flatpak_node_generator", "tests"]

[tool.mypy]
python_version = "3.8"
exclude = "^(.*/)?((([^/]+)-quick-start)|(\\.venv)|npm-cache|yarn-mirror)/.*$"
strict = true

[tool.poe.tasks]
check-format = "blue --check flatpak_node_generator tests"
check-isort = "isort --check flatpak_node_generator tests"
check-mypy = "mypy ."
check-test = "pytest -n auto"
check = ["check-format", "check-isort", "check-mypy", "check-test"]

apply-format = "blue flatpak_node_generator"
apply-isort = "isort flatpak_node_generator"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
