name: CI

on:
  push:
    paths:
      - deno/**
    branches:
      - master
  pull_request:
    paths:
      - deno/**
    branches:
      - master

defaults:
  run:
    working-directory: deno

permissions:
  contents: read

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run doc linter
        run: deno doc --lint src/main.ts

      - name: Run type check
        run: deno check .

      - name: Run tests
        run: deno test -A
