name: CI

on:
  push:
    branches: master
    paths:
      - pip/**
  pull_request:
    branches: master
    paths:
      - pip/**

defaults:
  run:
    working-directory: pip

jobs:
  pip:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Install uv
        # 5.4.0
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174
        with:
          version: "0.6.9"
          enable-cache: true
          cache-dependency-glob: |
            **/uv.lock
            **/pyproject.toml

      - name: Install python dependencies
        run: uv sync -v --all-groups --frozen

      - name: Check code formatting
        run: uv run ruff format --check

      - name: Lint
        run: uv run ruff check --output-format=github

      - name: Check python types
        run: uv run mypy .
