name: CI

on:
  push:
    branches: master
    paths:
      - poetry/**
  pull_request:
    branches: master
    paths:
      - poetry/**

defaults:
  run:
    working-directory: poetry

jobs:
  poetry:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
        # 4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Setup Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          sudo ln -s /github/home/.local/bin/poetry /usr/bin/poetry

      - name: Install python dependencies
        run: poetry sync --all-groups --all-extras

      - name: Check code formatting
        run: poetry run ruff format --check

      - name: Lint
        run: poetry run ruff check --output-format=github

      - name: Check python types
        run: poetry run mypy .
